In [1]:
import numpy as np
import pyemma

In [2]:
np.random.seed(0)
fake_trajectory = np.random.choice([0, 1, 2], size=1000, p=[0.6, 0.3, 0.1])

In [3]:
from pyemma.msm import estimate_markov_model
msm = estimate_markov_model(fake_trajectory, lag=1)

In [4]:
print("Transition matrix:")
print(msm.transition_matrix)
print("\nStationary distribution:")
print(msm.stationary_distribution)

Transition matrix:
[[0.60983607 0.28433688 0.10582705]
 [0.61407296 0.27402135 0.11190569]
 [0.59671759 0.2921713  0.11111111]]

Stationary distribution:
[0.60961373 0.28227211 0.10811416]


In [5]:
msm_lag5 = estimate_markov_model(fake_trajectory, lag=5)
print("Transition matrix (lag=5):")
print(msm_lag5.transition_matrix)
print("\nStationary distribution (lag=5):")
print(msm_lag5.stationary_distribution)

Transition matrix (lag=5):
[[0.62108731 0.27711308 0.1017996 ]
 [0.60068455 0.28469751 0.11461794]
 [0.57203403 0.29712484 0.13084112]]

Stationary distribution (lag=5):
[0.61002036 0.28141996 0.10855968]


In [6]:
# A trajectory where state 0 tends to stay in itself (a "trap")
fake_sticky = []
state = 0
for _ in range(1000):
    fake_sticky.append(state)
    if state == 0:
        state = np.random.choice([0, 1], p=[0.9, 0.1])  # sticky trap
    else:
        state = np.random.choice([0, 1, 2], p=[0.3, 0.3, 0.4])

fake_sticky = np.array(fake_sticky)
msm_sticky = estimate_markov_model(fake_sticky, lag=1)
print(msm_sticky.transition_matrix)

[[0.8697479  0.10714286 0.02310924]
 [0.47222222 0.16666667 0.36111111]
 [0.13414634 0.47560976 0.3902439 ]]


In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
# Simple 3-node graph: 0 -- 1 -- 2, with 0 being a "trap"
# Adjacency matrix
A = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0]
])

# Graph Laplacian: L = D - A
D = np.diag(A.sum(axis=1))
L = D - A
print("Laplacian:")
print(L)

Laplacian:
[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]


In [3]:
# Classical continuous-time random walk: dp/dt = -L p
# Solution: p(t) = exp(-Lt) p(0)
p0 = np.array([1.0, 0.0, 0.0])  # start fully at node 0
for t in [0, 1, 2, 5, 10]:
    p_t = la.expm(-L * t) @ p0
    print(f"t={t}: {p_t}")

t=0: [1. 0. 0.]
t=1: [0.5255709  0.31673764 0.15769146]
t=2: [0.4014141  0.33250708 0.26607882]
t=5: [0.33670236 0.33333323 0.32996441]
t=10: [0.33335603 0.33333333 0.33331063]


In [1]:
import numpy as np
import scipy.linalg as la

# Same 3-node graph as before
A = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0]
])

D = np.diag(A.sum(axis=1))
L = D - A

# Classical
p0 = np.array([1.0, 0.0, 0.0])
print("Classical diffusion:")
for t in [0, 1, 2, 5, 10]:
    p_t = la.expm(-L * t) @ p0
    print(f"t={t}: {np.round(p_t, 3)}")

# Quantum — only change is -1j
psi0 = np.array([1.0+0j, 0.0+0j, 0.0+0j])
print("\nQuantum walk:")
for t in [0, 1, 2, 5, 10]:
    psi_t = la.expm(-1j * L * t) @ psi0
    prob_t = np.abs(psi_t)**2
    print(f"t={t}: {np.round(prob_t, 3)}")

Classical diffusion:
t=0: [1. 0. 0.]
t=1: [0.526 0.317 0.158]
t=2: [0.401 0.333 0.266]
t=5: [0.337 0.333 0.33 ]
t=10: [0.333 0.333 0.333]

Quantum walk:
t=0: [1. 0. 0.]
t=1: [0.39  0.442 0.168]
t=2: [0.248 0.009 0.743]
t=5: [0.259 0.391 0.35 ]
t=10: [0.194 0.188 0.618]
